# Generated by Django 5.0.3 on 2024-05-22 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0003_alter_cryptowallets_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobOpportunities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, verbose_name='Name of company')),
                ('field_of_activity', models.CharField(blank=True, max_length=500, verbose_name='Field of activity')),
                ('salary', models.CharField(blank=True, max_length=500, verbose_name='Salary')),
                ('country', models.CharField(max_length=500, verbose_name='Country of office')),
            ],
            options={
                'verbose_name': 'Job Opportunity',
                'verbose_name_plural': 'Job Opportunities',
            },
        ),
    ]
