# Generated by Django 5.0.3 on 2024-09-02 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0006_ideasforprojects_remove_yourmodel_primary_language_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='IdeasForProjects',
            new_name='MyProjects',
        ),
        migrations.AlterModelOptions(
            name='myprojects',
            options={'verbose_name': 'My Project', 'verbose_name_plural': 'My Projects'},
        ),
    ]
