# Generated by Django 5.0.3 on 2024-09-02 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0007_rename_ideasforprojects_myprojects_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myprojects',
            name='name',
            field=models.CharField(max_length=500, verbose_name='Project name'),
        ),
        migrations.AlterField(
            model_name='myprojects',
            name='time',
            field=models.DateField(verbose_name='Duration'),
        ),
    ]
